# Site wide configuration

title:            Kartik Kannapur
locale:           en_US
url:              http://kartikkannapur.com/


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Kartik Kannapur
  avatar: KartikKannapur.jpg
  bio: "Geek | Foodie | Data Enthusiast"
  email: kartikkannapur@gmail.com
  disqus-shortname: 
  twitter: KartikKannapur
  facebook: #username
  google:
    plus: KartikKannapur27
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: KartikKannapur
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: kartikkannapur
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
