# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Kartik Kannapur"
description: "Welcome to my corner of the Internet"

email: kartikkannapur@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Kartik Kannapur'
author: 'Kartik Kannapur'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "kartikkannapur.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@KartikKannapur'

#fill in disqus shortname to use disqus
disqus: KartikKannapur

# social icons and sharing options
social:

  - icon: linkedin
    url:  https://in.linkedin.com/in/kartikkannapur
    desc: Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	github.com/KartikKannapur
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: twitter
    url:  http://twitter.com/KartikKannapur
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=Article by @KartikKannapur 
    share_link: "&amp;url="