title: "Kartik Kannapur"
author: "Kartik Kannapur"
description: "Welcome to my corner of the Internet"
more: "read more »"
url: "kartikkannapur.github.io" # the base hostname & protocol for your site
baseurl: ""
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md
  - learning.md

disqus: KartikKannapur

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - linkedin: "https://www.linkedin.com/in/kartikkannapur/"
  - github: "https://github.com/KartikKannapur"
  - twitter: "https://twitter.com/KartikKannapur"
  - envelope: "mailto:kartikkannapur@gmail.com"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
